services:
  dev:
    volumes:
      - .:/home/vscode/workspace
      - ./.ci-cache/conan2:/home/vscode/.conan2
      - ./.ci-cache/node_modules:/home/vscode/workspace/frontend/node_modules
      - ./.ci-cache/pip:/home/vscode/.cache/pip
